# Build the container image
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - "-t"
      - 'gcr.io/candidates/src-helloCsharp-$BRANCH_NAME:$COMMIT_SHA'
      - '-f'
      - 'HelloCSharp/Dockerfile'
      - '.'
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/candidates/src-helloCsharp-$BRANCH_NAME:$COMMIT_SHA'
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'srv-helloCsharp'
      - '--image'
      - 'gcr.io/candidates/src-helloCsharp-$BRANCH_NAME:$COMMIT_SHA'
      - '--port'
      - '8982'
      - '--region'
      - 'europe-west1'
images:
  - gcr.io/candidates/src-helloCsharp-$BRANCH_NAME:$COMMIT_SHA